import effect from "@mpsuesser/oxlint-plugin-effect";
import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import vitest from "ultracite/oxlint/vitest";

const antiSlopRules = [
  "no-array-filter-map",
  "no-chained-type-assertions",
  "no-conditional-empty-object-spread",
  "no-known-value-widening",
  "no-module-mocking",
  "no-object-parameters",
  "no-reduce-accumulator-copy",
  "no-reflect-apply",
  "no-reflect-get",
  "no-runtime-typeof",
  "no-shape-in-symbol-names",
  "no-unknown-parameters",
  "no-unknown-returns",
  "no-unknown-type-aliases",
  "no-unsafe-dictionary-type",
  "no-widen-then-assert",
  "require-readable-spacing",
  "require-safety-comment-for-type-assertion",
] as const;

const duplicateEffectRules = [
  "no-chained-type-assertions",
  "no-conditional-empty-object-spread",
  "no-known-value-widening",
  "no-module-mocking",
  "no-object-parameters",
  "no-reflect-apply",
  "no-reflect-get",
  "no-runtime-typeof",
  "no-shape-in-symbol-names",
  "no-unknown-parameters",
  "no-unknown-returns",
  "no-unknown-type-aliases",
  "no-unsafe-dictionary-type",
  "no-widen-then-assert",
  "require-safety-comment-for-type-assertion",
] as const;

export default defineConfig({
  extends: [core, vitest],
  env: { builtin: true, node: false },
  ignorePatterns: [
    "coverage/**",
    "contracts/**",
    "dist/**",
    "src/generated/**",
    "tools/oxlint/anti-slop/**",
  ],
  options: {
    denyWarnings: false,
    reportUnusedDisableDirectives: "off",
    typeAware: false,
    typeCheck: false,
  },
  plugins: [
    "eslint",
    "typescript",
    "unicorn",
    "oxc",
    "import",
    "jsdoc",
    "node",
    "promise",
    "vitest",
  ],
  jsPlugins: [
    { name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
    { name: "effect", specifier: "@mpsuesser/oxlint-plugin-effect" },
  ],
  rules: {
    ...Object.fromEntries(
      Object.keys(effect.rules).map((rule) => [`effect/${rule}`, "warn"])
    ),
    ...Object.fromEntries(
      antiSlopRules.map((rule) => [`anti-slop/${rule}`, "warn"])
    ),
    ...Object.fromEntries(
      duplicateEffectRules.map((rule) => [`effect/${rule}`, "off"])
    ),
    // These model external JSON, configuration, and SDK callback boundaries.
    // Option would change wire shapes; the SDK controls callback execution.
    "effect/avoid-process-env": "off",
    "effect/casting-awareness": "off",
    "effect/effect-run-in-body": "off",
    "effect/prefer-option-over-null": "off",
    // Luca disables these Ultracite style rules; the MCP manifest and tests
    // deliberately use semantic field order and explicit matcher forms.
    "class-methods-use-this": "off",
    "func-names": "off",
    "func-style": "off",
    "max-classes-per-file": "off",
    "no-await-in-loop": "off",
    "no-bitwise": "off",
    "no-inline-comments": "off",
    "no-plusplus": "off",
    "no-shadow": "off",
    "no-use-before-define": "off",
    "prefer-destructuring": "off",
    "prefer-named-capture-group": "off",
    "require-await": "off",
    "require-unicode-regexp": "off",
    "sort-keys": "off",
    "no-redeclare": "off",
    "import/consistent-type-specifier-style": "off",
    "import/first": "off",
    "promise/avoid-new": "off",
    "promise/prefer-await-to-callbacks": "off",
    "typescript/array-type": "off",
    "typescript/consistent-type-definitions": "off",
    "typescript/consistent-type-imports": "off",
    "typescript/no-dynamic-delete": "off",
    "typescript/no-explicit-any": "off",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/filename-case": "off",
    "unicorn/import-style": "off",
    "unicorn/no-array-for-each": "off",
    "unicorn/no-array-method-this-argument": "off",
    "unicorn/no-await-expression-member": "off",
    "unicorn/no-object-as-default-parameter": "off",
    "unicorn/no-unreadable-array-destructuring": "off",
    "unicorn/no-useless-undefined": "off",
    "unicorn/numeric-separators-style": "off",
    "unicorn/prefer-spread": "off",
    "unicorn/prefer-string-replace-all": "off",
    "unicorn/throw-new-error": "off",
    "oxc/no-accumulating-spread": "error",
    "oxc/no-barrel-file": "error",
  },
  overrides: [
    {
      files: ["scripts/**/*.{ts,js}", "**/*.config.ts", "oxlint.config.ts"],
      env: { node: true },
      rules: {
        // Build and release scripts use host APIs and process errors at the CLI boundary.
        "effect/prefer-option-over-null": "off",
        "effect/use-filesystem-service": "off",
        "effect/use-path-service": "off",
        "effect/avoid-sync-fs": "off",
        "effect/avoid-native-object-helpers": "off",
        "effect/imperative-loops": "off",
        "effect/avoid-untagged-errors": "off",
        "effect/use-console-service": "off",
        "effect/avoid-native-fetch": "off",
        "effect/avoid-try-catch": "off",
        "effect/use-command-executor-service": "off",
        "effect/avoid-node-imports": "off",
        "effect/avoid-direct-json": "off",
        "effect/no-length-comparison": "off",
        "effect/prefer-arr-match": "off",
      },
    },
    {
      files: ["test/**/*.{ts,js}", "**/*.{test,spec}.ts"],
      env: { node: true, vitest: true },
      rules: {
        // Test fixtures use host APIs and unsafe casts to exercise malformed inputs.
        "effect/avoid-ts-ignore": "off",
        "effect/require-schema-type-alias": "off",
        "effect/use-filesystem-service": "off",
        "effect/use-path-service": "off",
        "effect/avoid-sync-fs": "off",
        "effect/avoid-node-imports": "off",
        "effect/avoid-native-object-helpers": "off",
        "effect/avoid-direct-json": "off",
        "effect/avoid-untagged-errors": "off",
        "effect/avoid-non-null-assertion": "off",
        "effect/use-command-executor-service": "off",
        "effect/use-temp-file-scoped": "off",
        "effect/imperative-loops": "off",
        "anti-slop/no-chained-type-assertions": "off",
        "anti-slop/no-module-mocking": "off",
        "anti-slop/no-unknown-parameters": "off",
        "anti-slop/no-unsafe-dictionary-type": "off",
        "anti-slop/require-safety-comment-for-type-assertion": "off",
        "eslint/no-promise-executor-return": "off",
        "eslint/no-unsafe-optional-chaining": "off",
        "typescript/no-non-null-assertion": "off",
        "vitest/max-expects": "off",
        "vitest/no-standalone-expect": "off",
        "vitest/prefer-called-once": "off",
        "vitest/prefer-called-with": "off",
        "vitest/prefer-describe-function-title": "off",
        "vitest/prefer-expect-resolves": "off",
        "vitest/prefer-expect-type-of": "off",
        "vitest/prefer-import-in-mock": "off",
        "vitest/prefer-mock-promise-shorthand": "off",
        "vitest/prefer-mock-return-shorthand": "off",
        "vitest/prefer-strict-equal": "off",
        "vitest/prefer-to-be-falsy": "off",
        "vitest/prefer-to-be-truthy": "off",
        "vitest/require-mock-type-parameters": "off",
        "vitest/require-to-throw-message": "off",
        "vitest/valid-expect": "off",
      },
    },
    {
      files: ["src/index.ts"],
      rules: { "oxc/no-barrel-file": "off" },
    },
  ],
});
