/**
 * Generates `src/generated/route-catalog.ts` from the API-key allowlist
 * snapshot `apps/api/api-key-policies.json`.
 *
 * The allowlist decides what an API key may reach. A tool that names a method,
 * path, scope set, or idempotency rule of its own is writing the same facts a
 * second time, and the two lists drifted for as long as both existed. Here the
 * catalog is the one copy: `op()` takes an id, and reads the rest off this
 * file. An id the API does not grant has no key in `ROUTE_CATALOG`, so it
 * fails to compile rather than shipping a tool that 403s.
 */
import * as Effect from "effect/Effect";

import { writeOrCheck } from "./lib/generated-file.ts";
import { exitWith, prettyJson, runScript, scriptMode } from "./lib/script.ts";
import { loadApiKeyPolicies } from "./load-openapi.ts";

type CatalogEntry = {
  readonly method: string;
  readonly path: string;
  readonly scopes: readonly string[];
  readonly idempotencyRequired: boolean;
};

function render(catalog: Record<string, CatalogEntry>): string {
  return `// Generated by scripts/generate-route-catalog.ts. Do not edit by hand.

/**
 * Every route an API key can reach, keyed by operation id, as
 * \`apps/api/api-key-policies.json\` declares it. \`op()\` in
 * \`../operations/registry.ts\` reads a route's method, path, scopes, and
 * idempotency rule from here, so a tool declares which route it is and nothing
 * about what that route grants.
 */
export const ROUTE_CATALOG = ${prettyJson(catalog)} as const;

/** An operation id the API-key allowlist grants. */
export type LucaRouteId = keyof typeof ROUTE_CATALOG;
`;
}

const program = Effect.fn("generate-route-catalog")(function* () {
  const mode = yield* scriptMode(
    "usage: generate-route-catalog.ts --write|--check"
  );

  const { policies, source } = yield* loadApiKeyPolicies();

  const catalog: Record<string, CatalogEntry> = {};

  yield* Effect.forEach(
    policies,
    (policy) => {
      if (catalog[policy.id]) {
        return exitWith([
          `${source} declares the operation id ${policy.id} twice.`,
        ]);
      }

      catalog[policy.id] = {
        method: policy.method,
        path: policy.path,
        scopes: policy.scopes,
        idempotencyRequired: policy.requireIdempotency === true,
      };

      return Effect.void;
    },
    { concurrency: 1, discard: true }
  );

  yield* writeOrCheck({
    mode,
    target: "src/generated/route-catalog.ts",
    content: render(catalog),
    staleMessage:
      "src/generated/route-catalog.ts is out of date. Run `bun run catalog:generate`.",
    syncMessage: "Route catalog is in sync",
  });
});

runScript(program());
