import * as Arr from "effect/Array";
import * as Effect from "effect/Effect";
import * as R from "effect/Record";
import * as Schema from "effect/Schema";
import * as SchemaRepresentation from "effect/SchemaRepresentation";

import type { OpenApiInputSpec } from "../src/openapi-schema.ts";
import { fieldsWhen, optionalField } from "../src/optional-field.ts";
import type { JsonObject } from "../src/serialization.ts";
import { runCodegen } from "./lib/openapi-codegen.ts";
import {
  cursorQueryParamOf,
  openApiInputFields,
} from "./lib/openapi-input-fields.ts";
import {
  jsonBody,
  type OpenApiOperation,
  type OpenApiParameter,
} from "./lib/openapi-operation.ts";
import { exitWith, prettyJson, runScript } from "./lib/script.ts";

type RouteInput = {
  readonly spec: OpenApiInputSpec;
  /** Effect Schema source for the route's input fields, as one `Schema.Struct`. */
  readonly fields: string;
};

function objectSchemaFromParameters(
  parameters: readonly OpenApiParameter[],
  location: "path" | "query"
): JsonObject | undefined {
  const selected = parameters.filter((parameter) => parameter.in === location);

  if (!Arr.isReadonlyArrayNonEmpty(selected)) {
    return;
  }

  const required = selected.flatMap((parameter) =>
    parameter.required ? [parameter.name] : []
  );

  return {
    type: "object",
    properties: R.fromEntries(
      Arr.map(selected, (parameter) => [parameter.name, parameter.schema ?? {}])
    ),
    ...fieldsWhen(Arr.isReadonlyArrayNonEmpty(required), { required }),
  };
}

function operationInput(operation: OpenApiOperation): OpenApiInputSpec {
  const parameters = operation.parameters ?? [];

  return {
    ...optionalField("path", objectSchemaFromParameters(parameters, "path")),
    ...optionalField("query", objectSchemaFromParameters(parameters, "query")),
    ...optionalField("body", jsonBody(operation.requestBody)),
  };
}

/**
 * The route's input fields as Effect Schema source. The fields are built with
 * the same conversion the output schemas use, then printed by Effect's code
 * generator, so the server loads finished schemas instead of converting JSON
 * Schema on every start.
 */
function fieldsSource(route: string, spec: OpenApiInputSpec) {
  const code = SchemaRepresentation.toCodeDocument(
    SchemaRepresentation.toMultiDocument(
      SchemaRepresentation.toRepresentation(
        Schema.Struct(openApiInputFields(spec)).ast
      )
    )
  );

  const [root] = code.codes;

  // The generated module imports only `Schema`. A named reference or an
  // auxiliary declaration would need more than that, and no route has one.
  return root === undefined || hasUnsupportedReferences(code)
    ? exitWith([
        `${route}: Effect printed an input schema with references or imports, which src/generated/openapi-inputs.ts cannot hold.`,
      ])
    : Effect.succeed(root.runtime);
}

function hasUnsupportedReferences(
  code: ReturnType<typeof SchemaRepresentation.toCodeDocument>
): boolean {
  return [
    !Arr.isReadonlyArrayEmpty(code.artifacts),
    !Arr.isReadonlyArrayEmpty(code.references.nonRecursives),
    !R.isEmptyRecord(code.references.recursives),
  ].includes(true);
}

/**
 * The runtime file: finished field schemas and cursor names. The raw specs they
 * came from stay out of it, because nothing at runtime reads them.
 */
function renderFields(inputs: Record<string, RouteInput>) {
  const fields = R.toEntries(inputs).map(
    ([route, input]) => `  ${prettyJson(route)}: ${input.fields}.fields,`
  );

  const cursorQueryParams = R.fromEntries(
    R.toEntries(inputs).flatMap(([route, input]) => {
      const param = cursorQueryParamOf(input.spec.query);

      return param === undefined ? [] : [[route, param] as const];
    })
  );

  return [
    "// Generated by scripts/generate-openapi-inputs.ts. Do not edit by hand.",
    'import * as Schema from "effect/Schema";',
    "",
    'import type { ToolFields } from "../openapi-schema.ts";',
    "",
    "/**",
    " * Each route's path, query, and body fields as Effect Schema, converted from",
    " * the specs in `openapi-input-specs.ts` when this file was generated.",
    " */",
    "export const OPENAPI_INPUT_FIELDS: Readonly<Record<string, ToolFields>> = {",
    ...fields,
    "};",
    "",
    "/** The query field each paginated route takes its page cursor in. */",
    `export const OPENAPI_CURSOR_QUERY_PARAMS: Readonly<Record<string, string>> = ${prettyJson(cursorQueryParams)};`,
    "",
  ].join("\n");
}

/**
 * The raw JSON Schema each route's fields were converted from. Tests read it to
 * check the conversion; `tsconfig.build.json` leaves it out of the package.
 */
function renderSpecs(inputs: Record<string, RouteInput>) {
  return [
    "// Generated by scripts/generate-openapi-inputs.ts. Do not edit by hand.",
    'import type { OpenApiInputSpec } from "../openapi-schema.ts";',
    "",
    `export const OPENAPI_INPUT_SPECS = ${prettyJson(R.map(inputs, (input) => input.spec))} as const satisfies Record<string, OpenApiInputSpec>;`,
    "",
  ].join("\n");
}

runScript(
  runCodegen({
    scriptName: "generate-openapi-inputs.ts",
    extract: (operation, route) => {
      const spec = operationInput(operation);

      return Effect.map(fieldsSource(route, spec), (fields): RouteInput => ({
        spec,
        fields,
      }));
    },
    files: [
      { target: "src/generated/openapi-inputs.ts", render: renderFields },
      { target: "src/generated/openapi-input-specs.ts", render: renderSpecs },
    ],
  })
);
