import * as Arr from "effect/Array";
import * as Effect from "effect/Effect";
import * as R from "effect/Record";

import type { JsonObject } from "../src/serialization.ts";
import { runCodegen } from "./lib/openapi-codegen.ts";
import { successBody } from "./lib/openapi-operation.ts";
import { prettyJson, runScript } from "./lib/script.ts";
import { sensitivePathsInJsonSchema } from "./lib/sensitive-paths.ts";

type RouteOutput = {
  /** `null` marks a route with no body, such as a 204. */
  readonly body: JsonObject | null;
  readonly redactedFields: readonly string[];
};

function renderGenerated(outputs: Record<string, RouteOutput>) {
  const bodies = R.map(outputs, (output) => output.body);

  // Only a route with a marked field gets an entry.
  const redactedFields = R.filter(
    R.map(outputs, (output) => output.redactedFields),
    Arr.isReadonlyArrayNonEmpty
  );

  return [
    "// Generated by scripts/generate-openapi-outputs.ts. Do not edit by hand.",
    'import type { JsonSchema } from "../openapi-schema.ts";',
    "",
    `export const OPENAPI_OUTPUTS = ${prettyJson(bodies)} as const satisfies Record<string, JsonSchema | null>;`,
    "",
    "/**",
    " * The response fields the API marks with `sensitive()`, per route. The API",
    " * blanks them for a key on the `redacted` tier.",
    " */",
    `export const OPENAPI_REDACTED_FIELDS = ${prettyJson(redactedFields)} as const satisfies Record<string, readonly string[]>;`,
    "",
  ].join("\n");
}

runScript(
  runCodegen({
    scriptName: "generate-openapi-outputs.ts",
    extract: (operation) => {
      const body = successBody(operation) ?? null;

      return Effect.succeed<RouteOutput>({
        body,
        redactedFields: sensitivePathsInJsonSchema(body ?? undefined),
      });
    },
    files: [
      { target: "src/generated/openapi-outputs.ts", render: renderGenerated },
    ],
  })
);
